### ISSUE TITLE
Make GHA for filing workshop issues

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/2023-chop-training-demo#10]
Rather than directly opening issues needed for workshop live demos, let's create a GHA to automagically file live demo issues, which can live in `live-demo-issues/...markdown files...`. This has a couple benefits:

- More concrete chance to have those issues reviewed
- Helps out with #9 - if we use the template again, much easier to get issues up and running

**Comment by jaclyn-taroni** [comment]
I'm going to set this as blocking #9
