### ISSUE TITLE
Use dual license if needed

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/2023-chop-training-demo#3]
From https://github.com/AlexsLemonade/2023-chop-training-demo/pull/2#pullrequestreview-1544177666, we may want a dual license for this repo, where code will stay `BSD-3` and non-code (e.g., docs), would be (edit) `CC-BY`. That said, it's unclear whether this repository will contain anythings besides code, so we'll see how development plays out! If we end up with non-code, we should transition to the dual license approach.

**Comment by jaclyn-taroni** [comment]
`CC-BY`, not `CC0`.

**Comment by sjspielman** [comment]
> `CC-BY`, not `CC0`.

thanks, edited!

**Comment by sjspielman** [comment]
Given #10, we probably do want the dual license here.
