### ISSUE TITLE
Create branch for leaving a review live demo

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/2023-chop-training-demo#5]
Related to https://github.com/AlexsLemonade/2023-chop-training/issues/16

Before the workshop, create an issue, branch, and associated pull request that expands an existing notebook exploring spotify variation with only PCA to also include UMAP. When writing that code, ensure several nice commits along the way (and maybe a `haaaaaands` one), _and_ ensure we have items to review with some low-hanging fruit -
- Do not set a seed
- Do not set an appropriate UMAP theme
  - review can ask to remove axis ticks, labels 
- Do not include sufficient markdown text contextualizing the code
- Do not include `sessionInfo()`
- Do not load the `umap` package, and similarly do not use `umap::umap()` (e.g., just `umap()`)
  - The PR/branch itself can include a rendered HTML, but upon review, I will find that the environment is not reproducible.
  - Leads me to also suggest to open up a new issue to add `renv` to the project overall

This branch can be created sooner rather than later since the relevant code will not conflict with anything else, but still will need to ensure the branch stays in sync with `main`! 

Checklist: 
- [x] Baseline notebook with just PCA added to repo
- [x] Issue created
- [x] Branch created with all code necessary for demo
- [x] PR filed

**Comment by sjspielman** [comment]
Baseline notebook merged with #6.

**Comment by sjspielman** [comment]
Since I'm going to be leaving the review here, we might do something a little sneaky so I am not quite as obviously both author and reviewer - 
- Name the branch `jaclyn-taroni/something something`
- I will do all the work in said branch, & write contents for the PR itself, but then send to @jaclyn-taroni to actually do the filing

...Just don't look too carefully at the author of each commit 🙃

**Comment by jaclyn-taroni** [comment]
If we'd prefer, I can do the work/make the commits as long as I have instructions. It seems like you'd just have to send me the completed notebook with missing seeds, etc., no?

**Comment by sjspielman** [comment]
> If we'd prefer, I can do the work/make the commits as long as I have instructions.

If you don't mind doing that, it's certainly fine by me! I think the code is pretty straightforward, so the final notebook should be mostly self-explanatory as "instructions."

**Comment by sjspielman** [comment]
See also #10 - when creating the associated issue, first write it as stand-alone markdown file as described. Then, the issue can get created by running the GHA.

**Comment by sjspielman** [comment]
Noting that @sjspielman will write the framework, send it behind the scenes to @jaclyn-taroni, who will create the branch and PR.

**Comment by sjspielman** [comment]
For helping set up future repos (see #12), I wonder if it actually makes sense to store the notebook intended to be in the PR for the live review demo in `.live-demo-issues`, which could maybe be renamed (?) to `.live-demo-content`. Also, bonus fewer things going on "behind the scenes!"

Edit: ooh, actually, double bonus? Can commits associated with this PR be cherry-picked in for the live-demo PR? It seems so to me as long we we don't delete the branch upon merge!

**Comment by sjspielman** [comment]
At this stage now that we have first two tasks done, I'm going to unassign myself from this issue and let @jaclyn-taroni take care of the rest (branch w/ code, and filing the PR).

edit - I think we should add the text of the PR into `.live-demo-contents/` before filing; either of us can do this, so let me know if you prefer for me to take care of it and I'll reassign myself here!

**Comment by sjspielman** [comment]
Make sure when adding PR contents to `.live-demo-contents` that it gets linked in the README! See https://github.com/AlexsLemonade/2023-chop-training-demo/pull/17#issuecomment-1662559123.
