### ISSUE TITLE
Templatize the repo before workshop

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/2023-chop-training-demo#9]
_Before_ teaching the workshop (i.e., before code gets merged in during live demos), we should make this repository a template repository in case we'd like to teach something like this again. Having this as a template will make future potential prep much lighter!

**Comment by jaclyn-taroni** [comment]
Just noting how I might accomplish this – create a new repo with a sensical name and import this repo into it during the quick setup process. Then, [make the new repo a template](https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-template-repository).

**Comment by jaclyn-taroni** [comment]
I'll pick this up once #25 and #26 go in today. Unassigning you, @sjspielman.

**Comment by jaclyn-taroni** [comment]
Done ✅  https://github.com/AlexsLemonade/git-code-review-live-demo
